### ISSUE TITLE
To-do list before v0.3.0 deployment

### ISSUE THREAD

**Issue by PetrCala** [PetrCala/Kiroku#64]
### Must do before release
- [x] Finish user profile pictures handling
- [x] Handle the flashing when opening a user's profile (or app too)
- [x] #69
- [x] Fix the bug where the unfriend modal does not appear on iOS
- [x] Fix Android permissions
- [x] #68

### Migrating to 0.3.0 database

Write a migration script that does the following:

- [x] Transform all users/uid/beta_key_id from string -> number
- [x] Add all nicknames for all users (from scratch)
- [x] Add a maintenance node
- [x] Clean up the potential remaining bugs from the currentSession vs. ongoingSession inconsistencies
- [x] Publish new rules
- [x] Delete current user session
- [x] Add user status node
- [x] Remove all sessions that include a 0 unit object
- [x] Migrate user preferences (small beer)

**Comment by PetrCala** [comment]
gr8 success, good hustle
